spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

cloud:
    aws:
      s3:
        bucketName: ${BUCKET_NAME}
      region:
        static: ${REGION}

      stack:
        auto: false
      credentials:
        accessKey: ${ACCESSKEY}
        secretKey: ${SECRETKEY}

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB
