spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  profiles:
    active: local
    include: oauth, app
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
