spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.id}
            client-secret: ${google.secret}
            redirect-uri: "https://dev.nangmancat.shop/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email
          kakao:
            client-id: ${kakao.id}
            redirect-uri: "https://dev.nangmancat.shop/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
          naver:
            client-id: ${naver.id}
            client-secret: ${naver.secret}
            redirect-uri: "https://dev.nangmancat.shop/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, profile_nickname
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
