#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/cat
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#      # show_sql: true
#        format_sql: true
#logging.level:
#  org.hibernate.SQL: debug
spring:
  datasource:
    url: umc-dev.c7ymkkisi15g.ap-northeast-2.rds.amazonaws.com
    username: root
    password: romanticcat
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 300MB