spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: "https://dev.nangmancat.shop/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email
