spring:
  datasource:
    url: jdbc:mysql://umc-dev.c7ymkkisi15g.ap-northeast-2.rds.amazonaws.com :3306/a-romantic-cat
    username: root
    password: romanticcat
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  profiles:
    active: local
    include: oauth, app
  redis:
    host: localhost
    port: 6379
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
